// <auto-generated />
using EmployeeService.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EmployeeService.Infrastructure.Migrations
{
    [DbContext(typeof(EmployeeDbContext))]
    [Migration("20260613235344_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EmployeeService.Domain.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("BasicSalary")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ConveyanceAllowance")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Designation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("HouseRentAllowance")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("MedicalAllowance")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("PfContributionPercent")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BasicSalary = 50000m,
                            ConveyanceAllowance = 3000m,
                            Department = "IT",
                            Designation = "Software Engineer",
                            HouseRentAllowance = 25000m,
                            MedicalAllowance = 5000m,
                            Name = "Abir Hossain",
                            PfContributionPercent = 10m
                        },
                        new
                        {
                            Id = 2,
                            BasicSalary = 80000m,
                            ConveyanceAllowance = 4000m,
                            Department = "IT",
                            Designation = "Senior Engineer",
                            HouseRentAllowance = 40000m,
                            MedicalAllowance = 6000m,
                            Name = "Nusrat Jahan",
                            PfContributionPercent = 10m
                        },
                        new
                        {
                            Id = 3,
                            BasicSalary = 70000m,
                            ConveyanceAllowance = 3500m,
                            Department = "HR",
                            Designation = "HR Manager",
                            HouseRentAllowance = 35000m,
                            MedicalAllowance = 5000m,
                            Name = "Karim Ahmed",
                            PfContributionPercent = 10m
                        },
                        new
                        {
                            Id = 4,
                            BasicSalary = 45000m,
                            ConveyanceAllowance = 2500m,
                            Department = "Finance",
                            Designation = "Accountant",
                            HouseRentAllowance = 22000m,
                            MedicalAllowance = 4000m,
                            Name = "Fatima Akter",
                            PfContributionPercent = 8m
                        },
                        new
                        {
                            Id = 5,
                            BasicSalary = 120000m,
                            ConveyanceAllowance = 5000m,
                            Department = "IT",
                            Designation = "Project Manager",
                            HouseRentAllowance = 60000m,
                            MedicalAllowance = 8000m,
                            Name = "Tanvir Rahman",
                            PfContributionPercent = 10m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
